base:
  api:
    url: http://host.docker.internal:8888
    credential:
      username: foo
      password: bar
  sandbox: /app/wrappers/compiler.sh
  #sandbox: null
  runtimeDirectory: /app/runtime
  compile:
    _base:
      timeout: 20000
      source: foo.c
      target: foo.exe
      sandboxArgs: "" # must not be null
    _gcc_stdc11:
      command: gcc
      args: foo.c -O2 -Wall -static -std=c11 -o foo.exe -lm
    _clang_stdc11:
      command: clang
      args: foo.c -O2 -Wall -static -std=c11 -o foo.exe -lm
    gcc8:
      extend: [_base, _gcc_stdc11]
      env:
        PATH: "/usr/bin"
    clang14:
      extend: [_base, _clang_stdc11]
      command: clang-14
      env:
        PATH: "/usr/bin"
  mq:
    connection:
      hostname: host.docker.internal
      username: root
      password: 123456
      heartbeat: 30
