base:
  api:
    url: http://host.docker.internal:8888
    credential:
      username: foo
      password: bar
  sandbox: "/app/wrappers/match-stage-1.py"
  runtimeDirectory: /tmp/runtime
  match:
    s1bin: ./challenger.exe
    s2bin: ./opponent.exe
    config: config.json
    summary: summary.json
    command: node
    args: /app/makyek-judge/.dist/bootstrap.js --config config.json
  mq:
    connection:
      hostname: host.docker.internal
      username: root
      password: 123456
      heartbeat: 30
