base:
  api:
    url: http://host.docker.internal:8888
    credential:
      username: foo
      password: bar
  sandbox: /app/wrappers/compiler.sh
  #sandbox: null
  runtimeDirectory: /app/runtime
  compile:
    _base:
      timeout: 20000
      source: foo.c
      target: foo.exe
      sandboxArgs: "" # must not be null
    _gcc11:
      command: gcc
      args: -O2 -Wall -static -lm -std=c11 -o foo.exe foo.c
    gcc51c11:
      extend: [_base, _gcc11]
      env:
        PATH: "/usr/bin"
  mq:
    connection:
      hostname: host.docker.internal
      username: root
      password: 123456
      heartbeat: 30
