version: "2.4"
services:
  jd-compile-1:
    image: makyek-jd:latest
    restart: always
    command: node .dist/jd.js --role compile
    volumes:
      - ./config.jd.yaml:/app/config.yaml:ro
    tmpfs:
      - /app/makyek-jd/logs:mode=770,uid=1000,gid=1000
      - /runtime:mode=770,uid=1000,gid=1000
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - makyek-jd

  jd-match-1:
    image: makyek-jd:latest
    restart: always
    command: node .dist/jd.js --role match
    volumes:
      - ./config.jd.yaml:/app/config.yaml:ro
    tmpfs:
      - /app/makyek-jd/logs:mode=770,uid=1000,gid=1000
      - /runtime:mode=770,uid=1000,gid=1000,exec
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - makyek-jd

networks:
  makyek-jd:
      