version: "2.4"
services:
  jd-compile-1: &jd-compile-template
    image: makyek-jd:latest
    restart: always
    command: node .dist/jd.js --role compile
    cpu_count: 1
    mem_limit: 2g
    memswap_limit: 2g
    volumes:
      - ./config.jd-compile.yaml:/app/makyek-jd/config.yaml:ro
      - ./wrappers:/app/wrappers:ro
    tmpfs:
      - /app/makyek-jd/logs:mode=770,uid=1000,gid=1000
      - /app/runtime:mode=770,uid=1000,gid=1000
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - makyek-jd

  jd-compile-2: 
    <<: *jd-compile-template

  jd-match-1: &jd-match-template
    image: makyek-jd:latest
    restart: always
    command: node .dist/jd.js --role match
    cpu_count: 1
    mem_limit: 2g
    memswap_limit: 2g
    volumes:
      - ./config.jd-match.yaml:/app/makyek-jd/config.yaml:ro
      - ./wrappers:/app/wrappers:ro
    tmpfs:
      - /app/makyek-jd/logs:mode=770,uid=1000,gid=1000
      - /app/runtime:mode=770,uid=1000,gid=1000,exec
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - makyek-jd

  jd-match-2: 
    <<: *jd-match-template

networks:
  makyek-jd:
